config/routes.rb
Rails.application.routes.draw do
  resources :shops do
    resources :accesses
    resources :official_photos
    resources :photos
    resources :reviews
  end
end

app/models/official_photo.rb
class OfficialPhoto < ActiveRecord::Base
  enum state: { published: 1, draft: 2 }
end

app/controllers/official_photos_controller.rb
class OfficialPhotosController < ApplicationController
  before_action :set_official_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_shop, only: [:index, :show]
  layout 'shop'

  def index
    @official_photos = @shop.official_photos
  end

  def show
  end

  def new
    @official_photo = OfficialPhoto.new
  end

  def edit
  end

  def create
    @official_photo = OfficialPhoto.new(official_photo_params)

    respond_to do |format|
      if @official_photo.save
        format.html { redirect_to @official_photo, notice: 'Official photo was successfully created.' }
        format.json { render :show, status: :created, location: @official_photo }
      else
        format.html { render :new }
        format.json { render json: @official_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @official_photo.update(official_photo_params)
        format.html { redirect_to @official_photo, notice: 'Official photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @official_photo }
      else
        format.html { render :edit }
        format.json { render json: @official_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @official_photo.destroy
    respond_to do |format|
      format.html { redirect_to official_photos_url, notice: 'Official photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_shop
      @shop = Shop.find(params[:shop_id])
    end

    def set_official_photo
      @official_photo = OfficialPhoto.find(params[:id])
    end

    def official_photo_params
      params.require(:official_photo).permit(:title, :description)
    end
end

app/helpers/official_photos_helper.rb
module OfficialPhotosHelper
end

app/views/official_photos/_form.html.erb
<%= form_for(@official_photo) do |f| %>
  <% if @official_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@official_photo.errors.count, "error") %> prohibited this official_photo from being saved:</h2>

      <ul>
      <% @official_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/official_photos/edit.html.erb
<h1>Editing Official Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @official_photo %> |
<%= link_to 'Back', official_photos_path %>

app/views/official_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Official Photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @official_photos.each do |official_photo| %>
      <tr>
        <td><%= official_photo.title %></td>
        <td><%= official_photo.description %></td>
        <td><%= link_to 'Show', shop_official_photo_path(@shop, official_photo) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/official_photos/new.html.erb
<h1>New Official Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', official_photos_path %>

app/views/official_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @official_photo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @official_photo.description %>
</p>

<%= link_to 'Back', shop_official_photos_path %>