config/routes.rb
Rails.application.routes.draw do
  resources :shops do
    resources :accesses
    resources :official_photos
    resources :photos
    resources :reviews
  end
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_access, only: [:show, :edit, :update, :destroy]

  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.all
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(access_params)

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render :show, status: :created, location: @access }
      else
        format.html { render :new }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accesses/1
  # PATCH/PUT /accesses/1.json
  def update
    respond_to do |format|
      if @access.update(access_params)
        format.html { redirect_to @access, notice: 'Access was successfully updated.' }
        format.json { render :show, status: :ok, location: @access }
      else
        format.html { render :edit }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access.destroy
    respond_to do |format|
      format.html { redirect_to accesses_url, notice: 'Access was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access
      @access = Access.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def access_params
      params.require(:access).permit(:how_to, :holiday)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/_form.html.erb
<%= form_for(@access) do |f| %>
  <% if @access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% @access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :how_to %><br>
    <%= f.text_area :how_to %>
  </div>
  <div class="field">
    <%= f.label :holiday %><br>
    <%= f.text_field :holiday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<h1>Editing Access</h1>

<%= render 'form' %>

<%= link_to 'Show', @access %> |
<%= link_to 'Back', accesses_path %>

app/views/accesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accesses</h1>

<table>
  <thead>
    <tr>
      <th>How to</th>
      <th>Holiday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accesses.each do |access| %>
      <tr>
        <td><%= access.how_to %></td>
        <td><%= access.holiday %></td>
        <td><%= link_to 'Show', access %></td>
        <td><%= link_to 'Edit', edit_access_path(access) %></td>
        <td><%= link_to 'Destroy', access, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access', new_access_path %>

app/views/accesses/new.html.erb
<h1>New Access</h1>

<%= render 'form' %>

<%= link_to 'Back', accesses_path %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>How to:</strong>
  <%= @access.how_to %>
</p>

<p>
  <strong>Holiday:</strong>
  <%= @access.holiday %>
</p>

<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>